# Generated by Django 5.2.1 on 2025-06-12 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_contactmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cotizacion',
            name='cliente',
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='estado',
            field=models.BooleanField(default=False),
        ),
    ]
