# Generated by Django 5.2.1 on 2025-06-19 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_caracteristica_producto_caracteristicas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='caracteristicas',
        ),
        migrations.AddField(
            model_name='producto',
            name='caracteristicas',
            field=models.ManyToManyField(blank=True, to='api.caracteristica'),
        ),
    ]
