services:
  backend:
    build:
      context: .
    container_name: api_hidrotek
    command: gunicorn main.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: always